name: Update Algolia Index

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed

jobs:
  scrape:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Algolia Scraper
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }} 
        run: |
          # Inject secrets into the placeholder config.json
          jq ".appId = \"$APPLICATION_ID\" | .apiKey = \"$API_KEY\"" config.json > temp_config.json
          
          docker run \
            -e APPLICATION_ID=$APPLICATION_ID \
            -e API_KEY=$API_KEY \
            -e "CONFIG=$(cat temp_config.json | jq -r tostring)" \
            algolia/docsearch-scraper